service: demo-domain-shotstack
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: demo
  region: ap-southeast-2
  logRetentionInDays: 30
  deploymentBucket:
    name: shotstack-serverless-deploys-${self:provider.region}
    blockPublicAccess: true
  environment:
    DOMAIN_API_KEY: ${env:DOMAIN_API_KEY}
    SHOTSTACK_API_KEY: ${env:SHOTSTACK_API_KEY}
    SHOTSTACK_HOST: ${env:SHOTSTACK_HOST}

package:
  exclude:
    - .env
    - .env.dist
    - package.json
    - package-lock.json
    - src/app.js
    - node_modules/aws-sdk/**
    - node_modules/**/aws-sdk/**

functions:
  shotstack:
    handler: src/handler/shotstack/handler.submit
    description: Demo - Domain slideshow render
    timeout: 15
    memorySize: 128
    events:
      - http:
          path: shotstack
          method: post
          cors: true
  status:
    handler: src/handler/shotstack/handler.status
    description: Demo - Domain slideshow status check
    timeout: 10
    memorySize: 128
    events:
      - http:
          path: shotstack/{id}
          method: get
          cors: true
  search:
    handler: src/handler/domain/handler.search
    description: Demo - Domain property search
    timeout: 10
    memorySize: 128
    events:
      - http:
          path: domain/search/{search}
          method: get
          cors: true
  property:
    handler: src/handler/domain/handler.property
    description: Demo - Domain property lookup
    timeout: 10
    memorySize: 128
    events:
      - http:
          path: domain/property/{id}
          method: get
          cors: true
